@startuml Sequenzdiagramm_Prometheus _EC2
actor Benutzer
participant "AWS EC2" as EC2
participant "Git Repository" as Git
participant "Script (IP Config)" as Script
participant "Prometheus RDS Exporter" as Exporter
participant "Podman" as Podman

Benutzer -> EC2: Erstellen der EC2-Instanz
EC2 -> Git: Klonen des Git Repos
Git -> Script: Start Scripts IP Config Prometheus
Script -> Exporter:  Download und Install RDS Exporter
Exporter -> Podman: Starten Podman Compose für Prometheus
@enduml

@startuml oltp_to_olap
participant "WMS (Online Transaction Processing)" as WMS
participant "ETL (Extract, Transform, Load)" as ETL
participant "DWH (Online Analytical Processing)" as DWH

WMS -> ETL: Extract
ETL -> DWH: Load
@enduml
