@startuml Sequenzdiagramm_Prometheus _EC2
actor Benutzer
participant "AWS EC2" as EC2
participant "Git Repository" as Git
participant "Script (IP Config)" as Script
participant "Prometheus RDS Exporter" as Exporter
participant "Podman" as Podman

Benutzer -> EC2: Erstellen der EC2-Instanz
EC2 -> Git: Klonen des Git Repos
Git -> Script: Start Scripts IP Config Prometheus
Script -> Exporter:  Download und Install RDS Exporter
Exporter -> Podman: Starten Podman Compose für Prometheus / Grafana
@enduml

@startuml oltp_to_olap
participant "WMS (Online Transaction Processing)" as WMS
participant "ETL (Extract, Transform, Load)" as ETL
participant "DWH (Online Analytical Processing)" as DWH

WMS -> ETL: Extract Data
ETL -> ETL: Transform Data
ETL -> DWH: Load Data
@enduml


@startuml Sequenzdiagramm_Deployment
actor Benutzer
participant "create_rds_instances.py" as RDS
participant "import_dump_wms.py" as WMS
participant "create_iam_role.py" as Role
participant "create_iam_policy.py" as Policy
participant "create_iam_instance_profile.py" as Profile
participant "create_ec2_instances_prometheus_rds_exporter.py" as EC2

Benutzer -> RDS: Erstellen RDS Instance
RDS -> WMS: Import WMS Dump
WMS -> Role: Erstellen IAM Role
Role -> Policy: Erstellen IAM Policy, Anhängen an Role
Policy -> Profile: Erstellen IAM Instance Profile, Anhängen an Role
Profile -> EC2: Erstellen EC2 Instance, starten Prometheus
@enduml

@startuml Prometheus
participant "Script" as Script
participant "Grafana Image" as Image
participant "Prometheus Container" as Container
participant "Prometheus Tragets" as Datasource
participant "Prometheus Rules" as Rules

Script -> Image: Download Prometheus Image
Image -> Container: Start Prometheus Container
Container -> Datasource: Import Prometheus Targets
Datasource -> Rules: Import Prometheus Rules
@enduml

@startuml Grafana
participant "Script" as Script
participant "Grafana Image" as Image
participant "Grafana Container" as Container
participant "Grafana Datasource" as Datasource
participant "Grafana Dashboard" as Dashboard

Script -> Image: Download Grafana Image
Image -> Container: Start Grafana Container
Container -> Datasource: Import Prometheus Datasource
Datasource -> Dashboard: Import AWS RDS Dashboards
@enduml