---
global:
  scrape_interval: 30s  # Set the scrape interval. Default is every 1 minute.
  evaluation_interval: 30s  # Evaluate rules every. The default is every 1 minute.
  scrape_timeout: 10s

# Scrape configuration
scrape_configs:
  - job_name: 'rds-exporter'
    static_configs:
      - targets: ['xxx.xxx.xxx.xxx:9043']

  - job_name: 'ec2-instance'
    static_configs:
      - targets: ['127.0.0.1:9100']

# Load alert rules
rule_files:
  - "rules.yml"