groups:
- name: rds_instance_alerts
  rules:
  # Alert rule for AWS RDS Exporter down.
  - alert: AWS RDS Exporter InstanceDown
    expr: up{job="rds-exporter"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "RDS Exporter Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute." 

  # Alert rule for RDS exporter errors
  - alert: AWS RDS Exporter Errors
    expr: rds_exporter_errors_total{job="rds-exporter"} > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "RDS Exporter {{ $labels.instance }} errors"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has RDS exporter errors."

  # Alert rule for instance that is unreachable for x minutes.
  - alert: AWS RDS DB sem-3-db-instance is down
    expr: rds_instance_status{dbidentifier="sem-3-db-instance"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "RDS Instance {{ $labels.dbidentifier }} down"
      description: "{{ $labels.dbidentifier }} has been down for more than 1 minute."

  # Alert rule no metrics for AWS RDS DB sem-3-db-instance 
  - alert: AWS RDS NoDataAlert
    expr: absent(rds_instance_status{dbidentifier="sem-3-db-instance"})
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "No data available for sem-3-db-instance"
      description: "No data available for the metric rds_instance_status with dbidentifier 'sem-3-db-instance'."

  # Alert rule for instance that has pending maintenance
  - alert: AWS RDS Instance Pending Maintenance
    expr: rds_instance_info{pending_maintenance="yes"} > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "RDS Instance {{ $labels.dbidentifier }} has pending maintenance"
      description: "RDS Instance {{ $labels.dbidentifier }} in region {{ $labels.aws_region }} has pending maintenance."

  # Alert rule for AWS EC2 Exporter down.
  - alert: AWS EC2 Prometheus Node Exporter Down
    expr: up{job="ec2-instance"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "EC2 Node Exporter Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute." 

  # Alert rule for EC2 service 
  - alert: AWS EC2 Prometheus RDS Exporter Service Down
    expr: node_systemd_unit_state{name="prometheus-rds-exporter.service",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "EC2 Service prometheus-rds-exporter.service is down"
      description: "The EC2 service prometheus-rds-exporter.service is down."
