groups:
- name: rds_instance_alerts
  rules:

  # Alert rule for AWS RDS Exporter down.
  - alert: AWS RDS Exporter InstanceDown
    expr: up{job="rds-exporter"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes." 

  # Alert rule for rds exporter errors
  - alert: AWS RDS Exporter Errors
    expr: rds_exporter_errors_total{job="rds-exporter"} > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} rds exporter errors."
  
  # Alert rule for instance that is unreachable for x minutes.
  - alert: AWS RDS DB sem-3-db-instance is down
    expr: rds_instance_status{dbidentifier="sem-3-db-instance"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

  # Alert rule for instance that has pending maintenance
  - alert: AWS RDS Instance Pending Maintenance
    expr: rds_instance_info{pending_maintenance="yes"} > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "RDS Instance {{ $labels.instance }} has pending maintenance"
      description: "RDS Instance {{ $labels.instance }} in region {{ $labels.aws_region }} has pending maintenance."

  # Alert rule for AWS EC2 Exporter down.
  - alert: AWS EC2 Prometheus Node Exporter Down
    expr: up{job="ec2-instance"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes." 

  # Alert rule for EC2 service 
  - alert: AWS EC2 Prometheus RDS Exporter Service Down
    expr: node_systemd_unit_state{name="prometheus-rds-exporter.service",state="active"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "EC2 Service {{ $labels.instance }} is down"
      description: "EC2 Service {{ $labels.instance }} is down."
