groups:
- name: rds_instance_alerts
  rules:

  # Alert rule for AWS RDS Exporter down.
  - alert: InstanceDown AWS RDS Exporter
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes." 

  # Alert rule for rds exporter errors
  - alert: AWS RDS Exporter Errors
    expr: rds_exporter_errors_total{instance="172.31.5.183:9043", job="rds-exporter"} > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} rds exporter errors."
  
  # Alert rule for instance that is unreachable for x minutes.
  - alert: AWS RDS DB sem-3-db-instance is down
    expr: rds_instance_status{dbidentifier="sem-3-db-instance"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

  # Alert rule for instance that has pending maintenance
  - alert: RDSInstancePendingMaintenance
    expr: rds_instance_info{pending_maintenance="yes"} > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "RDS Instance {{ $labels.instance }} has pending maintenance"
      description: "RDS Instance {{ $labels.instance }} in region {{ $labels.aws_region }} has pending maintenance."
