{
 "title": "Prometheus RDS exporter",
 "description": "Prometheus RDS exporter internal metrics",
 "tags": [
  "dmf",
  "misc"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(rds_exporter_build_info{}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Exporters",
   "type": "stat",
   "description": "Number of Prometheus RDS exporter",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_exporter_build_info{instance=~\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "Exporter status",
   "type": "stat",
   "description": "Status of RDS exporters",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg(up{} * on (instance) rds_exporter_build_info{instance=~\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Number of errors reported by RDS exporters",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rds_exporter_errors_total{instance=~\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "AWS accounts",
   "type": "stat",
   "description": "Number of AWS accounts monitored by RDS exporters",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "count(\n    sum by (aws_account_id) (rds_instance_info{instance=~\"$instance\"})\n)\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RDS instances",
   "type": "stat",
   "description": "Number of AWS RDS instances monitored by RDS exporters",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rds_instance_info{instance=~\"$instance\"})\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RDS exporters",
   "type": "table",
   "description": "List of RDS exporters",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rds_exporter_build_info{instance=~\"$instance\"}\n"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 11 } },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "description": "Number of RDS exporter errors per minute",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(rds_exporter_errors_total{instance=~\"$instance\"}[1m]) * 60) by (instance)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "API calls", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 19 } },
  {
   "title": "AWS API calls per minute",
   "type": "timeseries",
   "description": "Number of HTTP calls to AWS APIs",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(rds_api_call_total{instance=~\"$instance\"}[5m]) * 60) by (api)\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "AWS API calls",
   "type": "stat",
   "description": "Total calls to AWS APIs to monitor RDS instances",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 20 },
   "targets": [
    {
     "expr": "sum(rds_api_call_total{instance=~\"$instance\"}) by (api)\n",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}