-- MySQL Script generated by MySQL Workbench
-- Tue May 21 07:51:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`status_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_code` (
  `status_codes` INT NOT NULL,
  `code_type` INT NULL,
  `code_bezeichnung` VARCHAR(45) NULL,
  PRIMARY KEY (`status_codes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`benutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`benutzer` (
  `id_benutzer` INT NOT NULL,
  `ref_status` INT NULL,
  `unsername` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `vorname` VARCHAR(45) NULL,
  PRIMARY KEY (`id_benutzer`),
  INDEX `fk_benutzer_1_idx` (`ref_status` ASC) VISIBLE,
  CONSTRAINT `fk_benutzer_1`
    FOREIGN KEY (`ref_status`)
    REFERENCES `mydb`.`status_code` (`status_codes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kunde` (
  `id_kunde` INT NOT NULL,
  `ref_status` INT NULL,
  `kundennummer` INT NULL,
  `name` VARCHAR(45) NULL,
  `rechnungsadresse` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kunde`),
  INDEX `fk_kunde_1_idx` (`ref_status` ASC) VISIBLE,
  CONSTRAINT `fk_kunde_1`
    FOREIGN KEY (`ref_status`)
    REFERENCES `mydb`.`status_code` (`status_codes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artikel` (
  `id_artikel` INT NOT NULL,
  `artikelnummer` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `gewicht` VARCHAR(45) NULL,
  `Seriennummer` TINYINT NULL,
  PRIMARY KEY (`id_artikel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lieferschein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lieferschein` (
  `id_lieferschein` INT NOT NULL,
  `ref_benutzer` INT NULL,
  `ref_kunde` INT NULL,
  `ref_status` INT NULL,
  `lieferadresse` VARCHAR(45) NULL,
  `bestell_datum` DATETIME NULL,
  `liefer_datum` DATE NULL,
  PRIMARY KEY (`id_lieferschein`),
  INDEX `fk_lieferschein_1_idx` (`ref_benutzer` ASC) VISIBLE,
  INDEX `fk_lieferschein_2_idx` (`ref_kunde` ASC) VISIBLE,
  INDEX `fk_lieferschein_3_idx` (`ref_status` ASC) VISIBLE,
  CONSTRAINT `fk_lieferschein_1`
    FOREIGN KEY (`ref_benutzer`)
    REFERENCES `mydb`.`benutzer` (`id_benutzer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieferschein_2`
    FOREIGN KEY (`ref_kunde`)
    REFERENCES `mydb`.`kunde` (`id_kunde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieferschein_3`
    FOREIGN KEY (`ref_status`)
    REFERENCES `mydb`.`status_code` (`status_codes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lieferschein_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lieferschein_position` (
  `id_lieferschein_position` INT NOT NULL,
  `ref_lieferschein` INT NULL,
  `ref_artikel` INT NULL,
  `menge` INT NULL,
  PRIMARY KEY (`id_lieferschein_position`),
  INDEX `fk_lieferschein_positionen_2_idx` (`ref_artikel` ASC) VISIBLE,
  INDEX `fk_lieferschein_positionen_1_idx` (`ref_lieferschein` ASC) VISIBLE,
  CONSTRAINT `fk_lieferschein_positionen_1`
    FOREIGN KEY (`ref_lieferschein`)
    REFERENCES `mydb`.`lieferschein` (`id_lieferschein`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieferschein_positionen_2`
    FOREIGN KEY (`ref_artikel`)
    REFERENCES `mydb`.`artikel` (`id_artikel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seriennummer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seriennummer` (
  `id_seriennummer` INT NOT NULL,
  `ref_lieferschein_position` INT NULL,
  `seriennummer` VARCHAR(45) NULL,
  PRIMARY KEY (`id_seriennummer`),
  INDEX `fk_seriennummer_1_idx` (`ref_lieferschein_position` ASC) VISIBLE,
  CONSTRAINT `fk_seriennummer_1`
    FOREIGN KEY (`ref_lieferschein_position`)
    REFERENCES `mydb`.`lieferschein_position` (`id_lieferschein_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`behaelter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`behaelter` (
  `id_behaelter` INT NOT NULL,
  `erstellt_datum` DATE NULL,
  `boxtype` VARCHAR(45) NULL,
  PRIMARY KEY (`id_behaelter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`behaelter_positionen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`behaelter_positionen` (
  `id_behaleter_positionen` INT NOT NULL,
  `ref_behaelter` INT NULL,
  `ref_lieferschein_positionen` INT NULL,
  PRIMARY KEY (`id_behaleter_positionen`),
  INDEX `fk_behaleter_positionen_1_idx` (`ref_behaelter` ASC) VISIBLE,
  INDEX `fk_behaleter_positionen_4_idx` (`ref_lieferschein_positionen` ASC) VISIBLE,
  CONSTRAINT `fk_behaleter_positionen_1`
    FOREIGN KEY (`ref_behaelter`)
    REFERENCES `mydb`.`behaelter` (`id_behaelter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_behaleter_positionen_4`
    FOREIGN KEY (`ref_lieferschein_positionen`)
    REFERENCES `mydb`.`lieferschein_position` (`id_lieferschein_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lagerplatz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lagerplatz` (
  `id_lagerplatz` INT NOT NULL,
  `ref_artikel` INT NULL,
  `platz` VARCHAR(45) NULL,
  `bestand` INT NULL,
  PRIMARY KEY (`id_lagerplatz`),
  INDEX `fk_lagerplatz_1_idx` (`ref_artikel` ASC) VISIBLE,
  CONSTRAINT `fk_lagerplatz_1`
    FOREIGN KEY (`ref_artikel`)
    REFERENCES `mydb`.`artikel` (`id_artikel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
