version: '3.1'
services:
  mysql:
    image: docker.io/mariadb:11.4.2
    environment:
      MYSQL_DATABASE: 'wms'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: mariadb-server-SQL
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: my-db
        target: /var/lib/mysql

volumes:
  my-db:
    driver: local
