version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - /opt/ITCNE23-SEM-III/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: docker.io/grafana/grafana:10.4.4
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - /opt/ITCNE23-SEM-III/grafana/provisioning/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - /opt/ITCNE23-SEM-III/grafana/provisioning/dashboards/rds-instance.json:/etc/grafana/provisioning/dashboards/rds-instance.json
      - /opt/ITCNE23-SEM-III/grafana/provisioning/dashboards/rds-instances.json:/etc/grafana/provisioning/dashboards/rds-instances.json
      - /opt/ITCNE23-SEM-III/grafana/provisioning/dashboards/prometheus-rds-exporter.json:/etc/grafana/provisioning/dashboards/prometheus-rds-exporter.json
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning

volumes:
  prometheus-data: {}
  grafana-storage: {}