version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - /opt/ITCNE23-SEM-III/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: docker.io/grafana/grafana:10.4.4
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - /opt/ITCNE23-SEM-I/monitoring/grafana/provisioning/dashboards/EC2-Instance.json:/etc/grafana/provisioning/dashboards/EC2-Instance.json
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning

volumes:
  prometheus-data: {}
  grafana-storage: {}