version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - /opt/ITCNE23-SEM-III/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
volumes:
  prometheus-data: {}