version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - /home/ubuntu/prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
volumes:
  prometheus-data: {}