name: Render PlantUML Diagrams
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render PlantUML diagrams
        uses: jdelobel/plantuml-render-action@v2
        with:
          source: '*.puml'
          output_type: png
          output_dir: 'bilder'
