name: Render PlantUML Diagrams
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install PlantUML
        run: |
          wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar

      - name: Render PlantUML diagrams
        run: |
          find . -type f -name "/diagrams/*.puml" -exec java -jar plantuml.jar -tpng {} \;

      - name: Copy generated PNG files to repository
        run: |
          mkdir -p diagrams
          mv *.png diagrams/
          git config --global user.email "roeschu.bluem@gmail.com"
          git config --global user.name "Blum"
          git add diagrams/
          git commit -m "Add generated PNG files "
          git push
