name: Beispielkonfiguration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Schritt 1
        run: echo "Dies ist ein Test"

      - name: Schritt 2
        run: echo "Ein weiterer Test"
